/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // './pages/**/*.{js,jsx,ts,tsx}',
    // './components/**/*.{js,jsx,ts,tsx}',
    // './styles/**/*.{css,scss}',

    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './views/**/*.{js,ts,jsx,tsx,mdx}',

    // Or if using `src` directory:
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontWeight: {
        'extra-bold': 800,
        bold: 700,
        regular: 400,
        light: 200,
      },
      colors: {
        custom: {
          darkGreen: '#161E11',
          green: '#1F6602',
          lightGreen: '#65F62A',
          gray: '#F0F0F0',
          lightGray: '#D8D8D8',
          darkGray: '#3A4334',
          paypal: '#179BD71A',
          yape: '#FEE89F',
          plin: '#83C2EB',
        },
      },
      fontSize: {
        h1: '64px',
        h2: '48px',
        h3: '36px',
        h4: '28px',
        h5: '24px',
        h6: '20px',
        base: '16px',
        sm: '14px',
        xs: '12px',
      },
      lineHeight: {
        h1: '75px',
        h2: '60px',
        h3: '48px',
        h4: '36px',
        h5: '30px',
        h6: '24px',
      },
      base: {
        fontFamily: 'plus-jakarta-sans',
      },
      maxWidth: {
        320: '320px',
        440: '440px',
        540: '540px',
        640: '640px',
        720: '720px',
        840: '840px',
      },
      maxHeight: {
        740: '740px',
      },
      width: {
        140: '140px',
        220: '220px',
        248: '248px',
        335: '335px',
        320: '320px',
        540: '540px',
        640: '640px',
      },
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#F0F0F0',
          'primary-content': '#333333',
          secondary: '#1F6602',
          'secondary-content': '#FFFFFF',
          accent: '#65F62A',
          'accent-content': '#333333',
          neutral: '#D8D8D8',
          'neutral-content': '#333333',
          'base-100': '#F0F0F0',
          'base-200': '#CCCCCC',
          'base-300': '#AAAAAA',
          'base-content': '#333333',
          info: '#007bff',
          'info-content': '#FFFFFF',
          success: '#28a745',
          'success-content': '#FFFFFF',
          warning: '#ffc107',
          'warning-content': '#333333',
          error: '#dc3545',
          'error-content': '#FFFFFF',
        },
        dark: {
          primary: '#161E11',
          'primary-content': '#FFFFFF',
          secondary: '#1F6602',
          'secondary-content': '#FFFFFF',
          accent: '#65F62A',
          'accent-content': '#333333',
          neutral: '#3A4334',
          'neutral-content': '#FFFFFF',
          'base-100': '#161E11',
          'base-200': '#2F3D2A',
          'base-300': '#495E42',
          'base-content': '#FFFFFF',
          info: '#007bff',
          'info-content': '#FFFFFF',
          success: '#28a745',
          'success-content': '#FFFFFF',
          warning: '#ffc107',
          'warning-content': '#333333',
          error: '#dc3545',
          'error-content': '#FFFFFF',
        },
      },
    ],
  },
}
